A custom message 2025-12-11T19:53:01Z

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -26,9 +26,14 @@ inputs:
     type: string
     default: ${{ github.head_ref || github.ref_name }}
   FILE_LIST:
-    description: "Path to a text file containing the list of file paths to be committed. Can be absolute or relative to the working directory."
+    description: "Absolute path to a text file containing the list of file paths to be committed."
     required: true
     type: string
+  WORKING_DIR:
+    description: "The absolute path for the working directory where the action will run."
+    required: false
+    type: string
+    default: ${{ github.workspace }}
   IS_DRY_RUN:
     description: "If set to true, the action will push the commits but leave them orphans (the head won't move.)"
     required: false
@@ -44,11 +49,6 @@ inputs:
     required: false
     type: string
     default: "Signed commit"
-  WORKING_DIR:
-    description: "The working directory where the action will run."
-    required: false
-    type: string
-    default: ${{ github.workspace }}
 
 outputs:
   sha:
@@ -76,7 +76,7 @@ runs:
           "https://api.github.com/repos/$TARGET_OWNER/$TARGET_REPO/git/refs/heads/$TARGET_REF" | jq -r '.ref // empty')
 
         if [[ -n "$branch_exists" ]]; then
-          echo "Branch '$TARGET_REF' already exists."
+          echo "::debug::Branch '$TARGET_REF' already exists."
           exit 0
         fi
 
@@ -135,7 +135,8 @@ runs:
         cat "$FILE_LIST"
         echo "::endgroup::"
 
-        max_batch_size=$((6 * 1024 * 1024)) # 7 MB in bytes
+        # Control batch size. We want larger files to be committed on their own for easier debugging.
+        max_batch_size=$((7 * 1024 * 1024)) 
         batch_files=()
         batch_size=0
         batch_file=$(mktemp)
@@ -153,7 +154,6 @@ runs:
           fi
 
           file_size=$(stat -c %s "$file_path")
-          # If adding this file would exceed the batch size, start a new batch
           if (( batch_size + file_size > max_batch_size )) && (( batch_size > 0 )); then
             echo "]" >> "$batch_file"
             batch_files+=("$batch_file")
@@ -178,7 +178,10 @@ runs:
                   -H "Accept: application/vnd.github+json" \
                   "$API/git/blobs" \
                   -d @- | jq -r '.sha')
-            echo "Binary content blob sha: $blob_sha"
+            if [[ -z "$blob_sha" ]]; then
+                echo "Error: Failed to create blob for binary file: $file_path"
+                exit 1
+            fi
 
             tree_entry=$(jq -n \
                 --arg path "$file_path" \
@@ -215,24 +218,24 @@ runs:
           batch_files+=("$batch_file")
         fi
 
-        echo "Get the latest commit"
+        echo "::debug::Get the latest commit"
         latest_commit=$(curl -s -H "Authorization: token $TOKEN" \
             "$API/git/refs/heads/$TARGET_REF" \
             | jq -r '.object.sha')
-        echo "Latest commit SHA: $latest_commit"
+        echo "::debug::Latest commit SHA: $latest_commit"
 
         if [[ -z "$latest_commit" ]]; then
             echo "Failed to retrieve the latest commit SHA for branch '$TARGET_REF'."
             if [[ "${inputs.SHOULD_CREATE_NEW_BRANCH}" == "false" ]]; then
-                echo "You have prevented the creation of branches that don't exist. If you regret it, set SHOULD_CREATE_NEW_BRANCH to true"
+                echo "You have prevented the creation of branches that don't exist. If that's not intentional, set SHOULD_CREATE_NEW_BRANCH to true"
                 exit 1
             fi
         fi
 
-        echo "Get the tree of the latest commit"
+        echo "::debug::Get the tree of the latest commit"
         base_tree=$(curl -s -H "Authorization: token $TOKEN" \
             "$API/git/commits/$latest_commit"| jq -r '.tree.sha')
-        echo "Base tree SHA: $base_tree"
+        echo "::debug::Base tree SHA: $base_tree"
 
         parent_commit="$latest_commit"
 
@@ -246,18 +249,18 @@ runs:
                     batch_filenames+=("$file_path")
                 fi
             done
+
             echo "Building tree. Total batch size: $batch_total_size bytes"
-            # if batch size is greater than 6MB print message
-            if (( batch_total_size > max_batch_size )); then
-                echo "Warning: Github limits tree sizes to 7MB. Reduce your file size."
-            fi
+            echo "::group::Tree file list"
             echo "Files in this batch: ${batch_filenames[*]}"
+            echo "::endgroup::"
+
             tree_json=$(jq -n \
               --arg base_tree "$base_tree" \
               --slurpfile tree_items "$batch_file" \
               '{base_tree: $base_tree, tree: $tree_items[0]}')
 
-            echo "Create new tree with GH API" 
+            echo "::debug::Create new tree with GH API" 
             response=$(echo "$tree_json" | \
                   curl -s -H "Authorization: token $TOKEN" -H "Accept: application/vnd.github+json" \
               -X POST "$API/git/trees" --data-binary @-)
@@ -267,7 +270,7 @@ runs:
                 echo "$response"
                 exit 1
             fi
-            echo "New tree sha: $new_tree"
+            echo "::debug::New tree sha: $new_tree"
 
             echo "Create commit with GH API (will be signed)"
             commit_json=$(jq -n \
@@ -279,19 +282,18 @@ runs:
             parent_commit=$(echo "$commit_json" | \
               curl -s -H "Authorization: token $TOKEN" -H "Accept: application/vnd.github+json" \
                 -X POST "$API/git/commits" --data-binary @- | jq -r '.sha')
-            echo "New parent commit sha: $parent_commit"
+            echo "::debug::New parent commit sha: $parent_commit"
 
-            echo "Update base_tree for next batch"
+            echo "::debug::Update base_tree for next batch"
             base_tree="$new_tree"
             rm "$batch_file"
-            echo "::endgroup::"
         done
 
         if [[ "${IS_DRY_RUN}" == "true" ]]; then
             echo "Dry run mode is enabled. The target branch head will not point to the new signed commit."
         else
             echo "Update the target branch with the new commit"
-            echo "Parent commit sha: $parent_commit"
+            echo "::debug::Parent commit sha: $parent_commit"
 
             move_head=$(curl -s -H "Authorization: token $TOKEN" -X PATCH \
               -d "{\"sha\":\"$parent_commit\"}" "$API/git/refs/heads/$TARGET_REF")
