chore: clean up logs

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -26,7 +26,7 @@ inputs:
     type: string
     default: ${{ github.head_ref || github.ref_name }}
   FILE_LIST:
-    description: "Path to a text file containing the list of file paths to be committed. Can be absolute or relative to the working directory."
+    description: "Absolute path to a text file containing the list of file paths to be committed."
     required: true
     type: string
   WORKING_DIR:
@@ -76,7 +76,7 @@ runs:
           "https://api.github.com/repos/$TARGET_OWNER/$TARGET_REPO/git/refs/heads/$TARGET_REF" | jq -r '.ref // empty')
 
         if [[ -n "$branch_exists" ]]; then
-          echo "Branch '$TARGET_REF' already exists."
+          echo "::debug::Branch '$TARGET_REF' already exists."
           exit 0
         fi
 
@@ -179,7 +179,9 @@ runs:
                   "$API/git/blobs" \
                   -d @- | jq -r '.sha')
             if [[ -z "$blob_sha" ]]; then
-                echo "===> Warning: Failed to create blob for binary file: $file_path"
+                echo "Error: Failed to create blob for binary file: $file_path"
+                exit 1
+            fi
 
             tree_entry=$(jq -n \
                 --arg path "$file_path" \
@@ -216,24 +218,24 @@ runs:
           batch_files+=("$batch_file")
         fi
 
-        echo "Get the latest commit"
+        echo "::debug::Get the latest commit"
         latest_commit=$(curl -s -H "Authorization: token $TOKEN" \
             "$API/git/refs/heads/$TARGET_REF" \
             | jq -r '.object.sha')
-        echo "Latest commit SHA: $latest_commit"
+        echo "::debug::Latest commit SHA: $latest_commit"
 
         if [[ -z "$latest_commit" ]]; then
             echo "Failed to retrieve the latest commit SHA for branch '$TARGET_REF'."
             if [[ "${inputs.SHOULD_CREATE_NEW_BRANCH}" == "false" ]]; then
-                echo "You have prevented the creation of branches that don't exist. If you regret it, set SHOULD_CREATE_NEW_BRANCH to true"
+                echo "You have prevented the creation of branches that don't exist. If that's not intentional, set SHOULD_CREATE_NEW_BRANCH to true"
                 exit 1
             fi
         fi
 
-        echo "Get the tree of the latest commit"
+        echo "::debug::Get the tree of the latest commit"
         base_tree=$(curl -s -H "Authorization: token $TOKEN" \
             "$API/git/commits/$latest_commit"| jq -r '.tree.sha')
-        echo "Base tree SHA: $base_tree"
+        echo "::debug::Base tree SHA: $base_tree"
 
         parent_commit="$latest_commit"
 
@@ -258,7 +260,7 @@ runs:
               --slurpfile tree_items "$batch_file" \
               '{base_tree: $base_tree, tree: $tree_items[0]}')
 
-            echo "Create new tree with GH API" 
+            echo "::debug::Create new tree with GH API" 
             response=$(echo "$tree_json" | \
                   curl -s -H "Authorization: token $TOKEN" -H "Accept: application/vnd.github+json" \
               -X POST "$API/git/trees" --data-binary @-)
@@ -268,7 +270,7 @@ runs:
                 echo "$response"
                 exit 1
             fi
-            echo "New tree sha: $new_tree"
+            echo "::debug::New tree sha: $new_tree"
 
             echo "Create commit with GH API (will be signed)"
             commit_json=$(jq -n \
@@ -280,19 +282,18 @@ runs:
             parent_commit=$(echo "$commit_json" | \
               curl -s -H "Authorization: token $TOKEN" -H "Accept: application/vnd.github+json" \
                 -X POST "$API/git/commits" --data-binary @- | jq -r '.sha')
-            echo "New parent commit sha: $parent_commit"
+            echo "::debug::New parent commit sha: $parent_commit"
 
-            echo "Update base_tree for next batch"
+            echo "::debug::Update base_tree for next batch"
             base_tree="$new_tree"
             rm "$batch_file"
-            echo "::endgroup::"
         done
 
         if [[ "${IS_DRY_RUN}" == "true" ]]; then
             echo "Dry run mode is enabled. The target branch head will not point to the new signed commit."
         else
             echo "Update the target branch with the new commit"
-            echo "Parent commit sha: $parent_commit"
+            echo "::debug::Parent commit sha: $parent_commit"
 
             move_head=$(curl -s -H "Authorization: token $TOKEN" -X PATCH \
               -d "{\"sha\":\"$parent_commit\"}" "$API/git/refs/heads/$TARGET_REF")
