A custom message 2025-12-11T16:22:40Z

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -26,14 +26,9 @@ inputs:
     type: string
     default: ${{ github.head_ref || github.ref_name }}
   FILE_LIST:
-    description: "Path to a text file containing the list of file paths to be committed. E.g.: subdir/file_paths.txt"
+    description: "Path to a text file containing the list of file paths to be committed. Can be absolute or relative to the working directory."
     required: true
     type: string
-  WORKING_DIR:
-    description: "The working directory where the action will run."
-    required: false
-    type: string
-    default: ${{ github.workspace }}
   IS_DRY_RUN:
     description: "If set to true, the action will push the commits but leave them orphans (the head won't move.)"
     required: false
@@ -49,6 +44,11 @@ inputs:
     required: false
     type: string
     default: "Signed commit"
+  WORKING_DIR:
+    description: "The working directory where the action will run."
+    required: false
+    type: string
+    default: ${{ github.workspace }}
 
 outputs:
   sha:
@@ -118,7 +118,7 @@ runs:
         FILE_LIST: ${{ inputs.FILE_LIST }}
         IS_DRY_RUN: ${{ inputs.IS_DRY_RUN }}
         COMMIT_MESSAGE: ${{ inputs.COMMIT_MESSAGE }}
-      working-directory: ${{ inputs.WORKING_DIR }}
+        WORKING_DIR: ${{ inputs.WORKING_DIR }}
       run: |
         #!/bin/bash
         set -euo pipefail
@@ -139,10 +139,14 @@ runs:
         echo "[" > "$tree_items_file"
         first=1
 
-        while IFS= read -r file_path; do
+        if [[ "$(pwd)" != "$WORKING_DIR" ]]; then
+          cd "$WORKING_DIR"
+        fi
 
+        while IFS= read -r file_path; do
+          
           if [[ ! -f "$file_path" ]]; then
-            echo "File not found: $file_path"
+            echo "Listed file $file_path not found."
             exit 1
           fi
 
@@ -161,6 +165,7 @@ runs:
                   -H "Accept: application/vnd.github+json" \
                   "$API/git/blobs" \
                   -d @- | jq -r '.sha')
+            echo "Binary content blob sha: $blob_sha"
 
             tree_entry=$(jq -n \
                 --arg path "$file_path" \
@@ -170,15 +175,15 @@ runs:
                 '{path: $path, mode: $mode, type: $type, sha: $sha}')
           else
             echo "Processing text file: $file_path"
-            temp_content=$(mktemp)
-            cat "$file_path" > "$temp_content"
+            temp_tree_content=$(mktemp)
+            cat "$file_path" > "$temp_tree_content"
             tree_entry=$(jq -n \
                 --arg path "$file_path" \
                 --arg mode "100644" \
                 --arg type "blob" \
-                --rawfile content "$temp_content" \
+                --rawfile content "$temp_tree_content" \
                 '{path: $path, mode: $mode, type: $type, content: $content}')
-            rm -f "$temp_content"
+            rm -f "$temp_tree_content"
           fi
 
           if [ $first -eq 1 ]; then
@@ -199,6 +204,8 @@ runs:
         latest_commit=$(curl -s -H "Authorization: token $TOKEN" \
             "$API/git/refs/heads/$TARGET_REF" \
             | jq -r '.object.sha')
+        echo "Latest commit SHA: $latest_commit"
+
         if [[ -z "$latest_commit" ]]; then
             echo "Failed to retrieve the latest commit SHA for branch '$TARGET_REF'."
             if [[ "${inputs.SHOULD_CREATE_NEW_BRANCH}" == "false" ]]; then
@@ -209,8 +216,8 @@ runs:
 
         echo "Get the tree of the latest commit"
         base_tree=$(curl -s -H "Authorization: token $TOKEN" \
-            "$API/git/commits/$latest_commit" \
-            | jq -r '.tree.sha')
+            "$API/git/commits/$latest_commit"| jq -r '.tree.sha')
+        echo "Base tree SHA: $base_tree"
 
         parent_commit="$latest_commit"
 
@@ -228,24 +235,34 @@ runs:
               --arg base_tree "$base_tree" \
               --slurpfile tree_items "$batch_file" \
               '{base_tree: $base_tree, tree: $tree_items[0]}')
-
+            echo "Tree JSON:"
+            echo "$tree_json"
             echo "Create new tree with GH API" 
-            new_tree_sha=$(echo "$tree_json" | \
-              curl -s -H "Authorization: token $TOKEN" -H "Accept: application/vnd.github+json" \
-                -X POST "$API/git/trees" --data-binary @- | jq -r '.sha')
+            response=$(echo "$tree_json" | \
+                  curl -s -H "Authorization: token $TOKEN" -H "Accept: application/vnd.github+json" \
+              -X POST "$API/git/trees" --data-binary @-)
+            new_tree=$(echo "$response" | jq -r '.sha // empty')
+            if [[ -z "$new_tree" ]]; then
+                echo "Failed to create new tree. Response:"
+                echo "$response"
+                exit 1
+            fi
+            echo "New tree sha: $new_tree"
 
             echo "Create commit with GH API (will be signed)"
             commit_json=$(jq -n \
               --arg msg "$COMMIT_MESSAGE $(date --utc +'%Y-%m-%dT%H:%M:%SZ')" \
-              --arg tree "$new_tree_sha" \
+              --arg tree "$new_tree" \
               --arg parent "$parent_commit" \
               '{message: $msg, tree: $tree, parents: [$parent]}')
+
             parent_commit=$(echo "$commit_json" | \
               curl -s -H "Authorization: token $TOKEN" -H "Accept: application/vnd.github+json" \
                 -X POST "$API/git/commits" --data-binary @- | jq -r '.sha')
+            echo "New parent commit sha: $parent_commit"
 
             echo "Update base_tree for next batch"
-            base_tree="$new_tree_sha"
+            base_tree="$new_tree"
             rm "$batch_file"
             echo "::endgroup::"
         done
@@ -254,10 +271,12 @@ runs:
             echo "Dry run mode is enabled. The target branch head will not point to the new signed commit."
         else
             echo "Update the target branch with the new commit"
+            echo "Parent commit sha: $parent_commit"
+
             move_head=$(curl -s -H "Authorization: token $TOKEN" -X PATCH \
               -d "{\"sha\":\"$parent_commit\"}" "$API/git/refs/heads/$TARGET_REF")
             if [[ $(echo "$move_head" | jq -r '.ref // empty') == "" ]]; then
-                echo "Failed to move the target branch head."
+                echo "Failed to move the target branch head. Parent commit SHA: $parent_commit"
                 echo "Response: $move_head"
                 exit 1
             fi
@@ -265,5 +284,5 @@ runs:
             echo "Target branch successfully updated with the new signed commit."
         fi
 
-        echo "New signed commit SHA:"
+        echo "New signed commit output:"
         echo "sha=$(echo $parent_commit)" | tee -a $GITHUB_OUTPUT
