A custom message 2025-12-09T16:41:37Z

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -139,12 +139,15 @@ runs:
         echo "[" > "$tree_items_file"
         first=1
 
+          if [[ ! -d "$WORKING_DIR" ]]; then
+            mkdir -p "$WORKING_DIR"
+          fi
+          cd "$WORKING_DIR"
+        
         while IFS= read -r file_path; do
           
-          full_path="${WORKING_DIR}/${file_path}"
-          
-          if [[ ! -f "$full_path" ]]; then
-            echo "Listed file $file_path not found on path $full_path"
+          if [[ ! -f "$file_path" ]]; then
+            echo "Listed file $file_path not found on path $file_path"
             exit 1
           fi
 
@@ -162,7 +165,15 @@ runs:
                   -H "Authorization: token $TOKEN" \
                   -H "Accept: application/vnd.github+json" \
                   "$API/git/blobs" \
-                  -d @- | jq -r '.sha')
+                  -d @-)
+            if [[ $(echo "$response" | jq -r '.sha // empty') == "" ]]; then
+              echo "Error creating blob for $file_path:"
+              echo "$response"
+              exit 1
+            fi
+
+            blob_sha=$(echo "$response" | jq -r '.sha')
+            sleep 5
 
             tree_entry=$(jq -n \
                 --arg path "$file_path" \
@@ -198,10 +209,11 @@ runs:
         batches=$(( (total_items + batch_size - 1) / batch_size ))
 
         echo "Get the latest commit"
-        sleep 2
         latest_commit=$(curl -s -H "Authorization: token $TOKEN" \
             "$API/git/refs/heads/$TARGET_REF" \
             | jq -r '.object.sha')
+        echo "Latest commit SHA (will become parent commit): $latest_commit"
+        sleep 5
         if [[ -z "$latest_commit" ]]; then
             echo "Failed to retrieve the latest commit SHA for branch '$TARGET_REF'."
             if [[ "${inputs.SHOULD_CREATE_NEW_BRANCH}" == "false" ]]; then
@@ -211,15 +223,14 @@ runs:
         fi
 
         echo "Get the tree of the latest commit"
-        sleep 2
         base_tree=$(curl -s -H "Authorization: token $TOKEN" \
-            "$API/git/commits/$latest_commit" \
-            | jq -r '.tree.sha')
+            "$API/git/commits/$latest_commit"| jq -r '.tree.sha')
+        echo "Base tree SHA: $base_tree"
+        sleep 5
 
         parent_commit="$latest_commit"
 
         for ((batch=0; batch<batches; batch++)); do
-            sleep 2
             echo "::group::Performing signed commit. Batch $((batch + 1)) of $batches"
             start=$((batch * batch_size))
             end=$((start + batch_size - 1))
@@ -235,24 +246,27 @@ runs:
               '{base_tree: $base_tree, tree: $tree_items[0]}')
 
             echo "Create new tree with GH API" 
-            sleep 2
-            new_tree_sha=$(echo "$tree_json" | \
+            new_tree=$(echo "$tree_json" | \
               curl -s -H "Authorization: token $TOKEN" -H "Accept: application/vnd.github+json" \
                 -X POST "$API/git/trees" --data-binary @- | jq -r '.sha')
+            echo "New tree sha: $new_tree"
+            sleep 5
 
-            echo "Create commit with GH API (will be signed)"
-            sleep 2
+            echo "Create commit with GH API (will be signed), Sleep 5 to avoid spamming the API"
             commit_json=$(jq -n \
               --arg msg "$COMMIT_MESSAGE $(date --utc +'%Y-%m-%dT%H:%M:%SZ')" \
-              --arg tree "$new_tree_sha" \
+              --arg tree "$new_tree" \
               --arg parent "$parent_commit" \
               '{message: $msg, tree: $tree, parents: [$parent]}')
+
             parent_commit=$(echo "$commit_json" | \
               curl -s -H "Authorization: token $TOKEN" -H "Accept: application/vnd.github+json" \
                 -X POST "$API/git/commits" --data-binary @- | jq -r '.sha')
+            echo "New parent commit sha: $parent_commit"
+            sleep 5
 
             echo "Update base_tree for next batch"
-            base_tree="$new_tree_sha"
+            base_tree="$new_tree"
             rm "$batch_file"
             echo "::endgroup::"
         done
@@ -261,9 +275,8 @@ runs:
             echo "Dry run mode is enabled. The target branch head will not point to the new signed commit."
         else
             echo "Update the target branch with the new commit"
-            echo "Parent commit: $parent_commit"
+            echo "Parent commit sha: $parent_commit"
 
-            sleep 2
             move_head=$(curl -s -H "Authorization: token $TOKEN" -X PATCH \
               -d "{\"sha\":\"$parent_commit\"}" "$API/git/refs/heads/$TARGET_REF")
             if [[ $(echo "$move_head" | jq -r '.ref // empty') == "" ]]; then
