Signed commit 2025-07-24T15:42:43Z

diff --git a/.github/workflows/test_action.yaml b/.github/workflows/test_action.yaml
--- a/.github/workflows/test_action.yaml
+++ b/.github/workflows/test_action.yaml
@@ -12,12 +12,22 @@ jobs:
     runs-on: ubuntu-latest
     name: Commit with bot verified commit
     env:
-      branch: ${{ github.event.pull_request.head.ref }}
+      pr_branch: ${{ github.event.pull_request.head.ref }}
+    strategy:
+      max-parallel: 1
+      fail-fast: false
+      matrix:
+        include:
+          - { test_type: existing_branch, ref_name: qa, should_create_branch: true, trigger_autodoc: false } #should_create_branch defaults to true
+          - { test_type: new_branch, should_create_branch: false, trigger_autodoc: false } 
+          - { test_type: new_branch, should_create_branch: true, trigger_autodoc: false }
+          - { trigger_autodoc: true }
+
 
     steps:
       - uses: actions/checkout@v4
         with:
-          ref: ${{ env.branch }}
+          ref: ${{ env.pr_branch }}
           fetch-depth: 0
           token: ${{ secrets.GITHUB_TOKEN }}
 
@@ -27,21 +37,44 @@ jobs:
           echo "$(git diff --name-only origin/qa...HEAD)" > file_list.txt
           cat file_list.txt
 
+      - name: Generate branch name
+        if: ${{ matrix.test_type == 'new_branch' }}
+        id: generate_branch_name
+        run: |
+          echo "Generating new branch name..."
+          # Generate a unique branch name based on UTC timestamp
+          now=$(date -u +"%Y%m%d%H%M%S")
+          echo "branch_name=qa-${now}" | tee -a $GITHUB_OUTPUT
+
       - name: Test action
         id: test
         uses: ./
+        continue-on-error: true
         with:
-          TARGET_REF: qa
+          TARGET_REF: ${{ matrix.ref_name || steps.generate_branch_name.outputs.branch_name }}
           FILE_LIST: file_list.txt
-
+          SHOULD_CREATE_NEW_BRANCH: ${{ matrix.should_create_branch }}
+      
+      - name: Handle failure
+        if: ${{ steps.test.outcome == 'failure' }}
+        run: |
+          # if test_type is new_branch and should_create_branch is false, we expect the action to fail
+          if [[ "${{ matrix.test_type }}" == "new_branch" && "${{ matrix.should_create_branch }}" == "false" ]]; then
+            echo "Expected failure for new branch without creation. Skipping validation."
+            exit 0
+          fi
+          echo "Action failed in unexpected way."
+          exit 1
+      
       - name: Validate commit
+        if: ${{ steps.test.outcome != 'failure' }}
         env:
           GH_TOKEN: ${{ github.token }}
           SHA: ${{ steps.test.outputs.sha }}
-          TARGET_REF: qa
+          TARGET_REF: ${{ matrix.ref_name || steps.generate_branch_name.outputs.branch_name }}
         run: |
           # Cool off
-          sleep 10
+          sleep 5
 
           # Get the latest commit SHA from the target branch
           latest_commit_sha=$(gh api repos/${{ github.repository }}/git/ref/heads/$TARGET_REF --jq '.object.sha')
@@ -68,6 +101,7 @@ jobs:
           fi
 
       - id: should_trigger
+        if: ${{ matrix.trigger_autodoc == true }}
         run: |
           echo "should_run=false" | tee -a $GITHUB_OUTPUT
             if git diff --name-only origin/main...HEAD | grep -qE 'action\.yaml|\.github/workflows/pr_action_docs\.yaml'; then
@@ -79,5 +113,5 @@ jobs:
         uses: peter-evans/repository-dispatch@v3
         with:
           event-type: action_test
-          client-payload: '{"ref": "${{ env.branch }}"}'
+          client-payload: '{"ref": "${{ env.pr_branch }}"}'
 
